pipeline {
    agent {
        any {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                withEnv(['PATH+EXTRA=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/.dotnet/tools:/root/bin']) {  
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                withEnv(['PATH+EXTRA=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/.dotnet/tools:/root/bin']) {  
                    sh './jenkins/scripts/test.sh'
                }
            }
        }
        stage('Deliver') {
            steps {
                withEnv(['PATH+EXTRA=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/.dotnet/tools:/root/bin']) {  
                   sh './jenkins/scripts/deliver.sh'
                   input message: 'Finished using the web site? (Click "Proceed" to continue)'
                   sh './jenkins/scripts/kill.sh'
                }
                
            }
        }
    }
}
